### ISSUE TITLE
SocketException: Operation not supported on .NET Core SDK v2.1.3 / linux-arm build.

### ISSUE THREAD

**Issue by idubnori** [novotnyllc/Zeroconf#96]
Repro steps
1. Call `EnumerateAllServicesFromAllHosts` which is the usage example.
It's on top of .NET Core 2 / console app.
2. Publish it for linux-arm platform. (`dotnet publish -r linux-arm`)
3. Run it on Raspberry Pi.
4. Observe Socket Exception the followings.
(Same code runs normally on Windows.)
```bash
Unhandled Exception: System.AggregateException: One or more errors occurred. (Operation not supported) ---> System.Net.Sockets.SocketException: Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_ExclusiveAddressUse(Boolean value)
   at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Zeroconf.ZeroconfResolver.<ResolveInternal>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Zeroconf.ZeroconfResolver.<BrowseDomainsAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Zeroconf.ZeroconfResolver.<BrowseDomainsAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ShairportSync.RemoteController.RemoteController.<GetRemoteClientAsync>d__0.MoveNext() in C:\Users\...\Documents\Visual Studio 2017\Projects\...RemoteController.cs:line 12
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleController.Program.<>c.<<Main>b__0_0>d.MoveNext() in C:\Users\...\Documents\Visual Studio 2017\Projects\...Program.cs:line 16
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConsoleController.Program.Main(String[] args)
```

**Comment by onovotny** [comment]
Can you pleaes file this in the CoreFX repo? This doesn't sound like anything that I can do here.

**Comment by idubnori** [comment]
Sure. I would do so. Thank you.

**Comment by idubnori** [comment]
Stack trace with project reference.

```
System.AggregateException: One or more errors occurred. (Operation not supported) ---> System.Net.Sockets.SocketException: Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_ExclusiveAddressUse(Boolean value)
   at System.Net.Sockets.UdpClient.set_ExclusiveAddressUse(Boolean value)
   at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__1.MoveNext() in C:\github\Zeroconf\Zeroconf\Platforms\netstandard\NetworkInterface.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__1.MoveNext() in C:\github\Zeroconf\Zeroconf\Platforms\netstandard\NetworkInterface.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__0.MoveNext() in C:\github\Zeroconf\Zeroconf\Platforms\netstandard\NetworkInterface.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Zeroconf.ZeroconfResolver.<ResolveInternal>d__9.MoveNext() in C:\github\Zeroconf\Zeroconf\ZeroconfResolver.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Zeroconf.ZeroconfResolver.<BrowseDomainsAsync>d__4.MoveNext() in C:\github\Zeroconf\Zeroconf\ZeroconfResolver.Async.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Zeroconf.ZeroconfResolver.<BrowseDomainsAsync>d__3.MoveNext() in C:\github\Zeroconf\Zeroconf\ZeroconfResolver.Async.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp1.Program.<>c.<<Main>b__0_0>d.MoveNext() in C:\github\Zeroconf\ConsoleApp1\Program.cs:line 14
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConsoleApp1.Program.Main(String[] args) in C:\github\Zeroconf\ConsoleApp1\Program.cs:line 12
Aborted
```

**Comment by clairernovotny** [comment]
Closing due to age.
